# Generated by Django 4.1.3 on 2023-02-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_web_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='two_factor_auth_enabled',
        ),
        migrations.AddField(
            model_name='myuser',
            name='one_factor_auth_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
