# Generated by Django 4.1.3 on 2023-02-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_web_interface', '0002_remove_myuser_two_factor_auth_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nfc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
